version: "3"
services:
  nginx_service:
    container_name: nginx_1.19_later
    image: nginx:1.19-alpine
    volumes:
      - ./templates:/etc/nginx/templates
    environment:
      - PORT=8080
    ports:
      - 3000:8080
